♻️ refactor(actions): rename type input to mode for clarity
- rename the `type` input to `mode` in both action files
- update the corresponding variable names in the bash scripts
- this change provides better clarity and reflects the intended usage of the input, which is to specify the extraction mode

diff --git a/.github/actions/get-version-array-from-versions-file/action.yml b/.github/actions/get-version-array-from-versions-file/action.yml
--- a/.github/actions/get-version-array-from-versions-file/action.yml
+++ b/.github/actions/get-version-array-from-versions-file/action.yml
@@ -6,7 +6,7 @@ name: get-version-array-from-versions-file
 description: Get the Version List from the versions.json file.
 
 inputs:
-  type:
+  mode:
     required: true    # [required]
     description: >
       Specifies the extraction mode. Accepted values are "group" for aggregating versions across a version group, or "single" for fetching a specific version.
@@ -50,7 +50,7 @@ runs:
       id: gvav
       shell: bash
       run: |
-        TYPE="${{ inputs.type }}"
+        MODE="${{ inputs.mode }}"
         VERSION="${{ inputs.version }}"
         VERSION_GROUP="${{ inputs.version-group }}"
         VERSION_FILTER="${{ inputs.version-filter }}"
@@ -59,7 +59,7 @@ runs:
 
         cd "${WORKING_DIRECTORY}"
 
-        if [[ "${TYPE}" == "group" ]]; then
+        if [[ "${MODE}" == "group" ]]; then
           if [[ "${VERSION_GROUP}" == "all" ]]; then
             VERSION_GROUP_FILTER=""
           else
@@ -78,7 +78,7 @@ runs:
           JQ_FILE="${VERSIONS_FILE}"
           OBJECT_LIST=$(jq -c "${JQ_FILTER}" "${JQ_FILE}")
           VERSION_ARRAY=$(echo "${OBJECT_LIST}" | jq -c "[.[].VERSION]")
-        elif [[ "${TYPE}" == "single" ]]; then
+        elif [[ "${MODE}" == "single" ]]; then
           if [[ "${VERSION_FILTER}" == "all" ]]; then
             JQ_FILTER="[.[] | map(.)] | add"
           elif [[ "${VERSION_FILTER}" == "gettext" ]]; then
@@ -100,7 +100,7 @@ runs:
           fi
           VERSION_ARRAY="[ \"${VERSION_VALUE}\" ]"
         else
-          echo "Error: Invalid TYPE value. (${TYPE})" >&2
+          echo "Error: Invalid MODE value. (${MODE})" >&2
           exit 1
         fi
 
